learngraph/learn-graph-frontend

src/GraphManager/GraphEdit.test.tsx, src/GraphManager/GraphEdit.tsx, src/GraphManager/GraphEditPopUp.tsx, src/GraphManager/GraphRenderer.tsx, src/GraphManager/components/HeaderBar.tsx, src/GraphManager/components/VoteDialog.tsx, src/UserDataContext.tsx
- display pop-up when non-logged in user tries to create graph data, so that they sign up!
- slider default position is always the center (may avoid confirmation bias)
- fix: slider value incorrect if user does not touch the slider after node-dragging and directly clicks confirm
=> feat: user not logged in popup & link slider value fix

src/App.tsx, src/GraphManager/GraphEdit.test.tsx, src/GraphManager/GraphEdit.testingutil.tsx, src/GraphManager/GraphEdit.tsx, src/GraphManager/GraphEditPopUp.tsx, src/GraphManager/GraphRenderer.test.tsx, src/GraphManager/GraphRenderer.tsx, src/GraphManager/hooks/types.ts, src/GraphManager/hooks/useDeleteEdge.ts, src/GraphManager/hooks/useDeleteNode.ts, src/Theme.tsx, src/i18n.ts
- users should be able to undo mistakes they made
- this PR enables deletion of your own (your user) nodes and edges, nothing else can be deleted
=> feat: delete nodes & edges

src/GraphManager/components/HeaderBar.tsx, src/GraphManager/components/LocaleManager.tsx, src/i18n.ts
- enables language switching (for UI and for graph backend!)
=> feat: language button

src/GraphManager/GraphEdit.test.tsx, src/GraphManager/GraphEdit.tsx, src/GraphManager/GraphEditPopUp.tsx, src/GraphManager/hooks/useCreateNode.ts, src/GraphManager/hooks/useGraphData.ts, src/GraphManager/hooks/useUpdateNode.ts, src/GraphManager/types.ts, src/UserDataContext.tsx, src/i18n.ts, src/shared/Styles.tsx
Implements the easiest solution: Always query all nodes with resources & just add it as formik field to every node-creation/edit.
=> feat: add resources field to nodes

src/GraphManager/GraphManager.tsx, src/GraphManager/GraphRenderer.tsx, src/GraphManager/SearchResultPopUp.test.tsx, src/GraphManager/SearchResultPopUp.tsx
Fixes the search results layout for mobile (bottom) and desktop (left side).
=> fix: search results layout

src/GraphManager/GraphEdit.test.tsx, src/GraphManager/GraphEdit.testingutil.tsx, src/GraphManager/GraphEdit.tsx, src/GraphManager/GraphEditCreateButton.tsx, src/GraphManager/GraphEditModeButton.tsx, src/GraphManager/GraphRenderer.test.tsx, src/GraphManager/GraphRenderer.tsx, src/i18n.ts
- disable user-graph interaction by default (not logged in user)
- enable create-button, once user is logged in
- enable manual edit-mode switch, once user is logged in
- display warnings, whenever a non-logged in user tries to enable editing, or graph interaction
=> feat: edit mode

src/GraphManager/GraphEdit/PopUp.tsx, src/shared/i18n.ts
* remove empty dialog content
* change texts
* remove elements moving 2px on hover
* change slider step to 0.1s
=> feat: cleanup around links display

src/App.tsx, src/Context/UserDataContext.test.tsx, src/Context/UserDataContext.tsx, src/GraphManager/GraphEdit/PopUp.tsx, src/GraphManager/GraphEdit/UserSettings.tsx, src/GraphManager/GraphRenderer.tsx, src/Navigation.tsx, src/Theme.tsx
Enable the config option "dark theme" that set's the canvas background as well as the mui theme to 'dark'.
=> feat: dark theme

src/GraphManager/GraphEdit/PopUp.tsx, src/LandingPage/FAQ.tsx, src/LandingPage/Hero.tsx, src/LandingPage/Highlights.tsx, src/shared/i18n.json
* fix the split of the string in the Hero element
* make the contents of the landing page use translation strings
=> Fix: clean up small landing page issues

src/GraphManager/GraphRenderer.tsx, src/GraphManager/Header/Search.tsx, src/GraphManager/RPCHooks/useGraphData.ts, src/GraphManager/types.ts, src/GraphManager/utils.ts
[This task](https://dev.learngraph.org/shared/br97wxbctpbbb88nfmd5b6es3mr/v841gaw19gif8zdmkr7urozierw/cwdj5nc4zyiyyzjtcg6dyqj1hsr?r=kp7bft7gdc4fqby49dpm5wewf6y).
Disables force simulation in the fronend.
Perform graph embedding (force simulation for graph layout) computation in the backend, the corresponding backend PR https://github.com/suxatcode/learn-graph-backend/pull/12 . The results are amazing. A simple stable graph embedding.
=> feat: use backend layout

.github/workflows/release.yml, Dockerfile
- add argument to Dockerfile to select architecture dependent nginx
image
- add matrix build to the release.yml github-action to pass those image
names separately for each architecture
=> fix: arm64 build

.github/workflows/release.yml
- build images for architectures with different image tags
- create a manifest to join the images under a single name
=> ci: finialize image builds for arm64 / amd64

.github/workflows/release.yml
- add github release versioning to the docker image
- push ':latest' image tag from branch main on every merge (unchanged!)
=> ci: deploy only on release

src/GraphManager/GraphEdit/GraphEdit.testingutil.tsx, src/GraphManager/GraphRenderer.tsx, src/GraphManager/utils.test.ts, src/GraphManager/utils.ts
- TODO: should differentiate (by color) between ingoing and outgoing links
=> feat: highlight connected nodes onHover

src/GraphManager/utils.test.ts, src/GraphManager/utils.ts
- remove links to node when node is deleted
- requires https://github.com/suxatcode/learn-graph-backend/pull/13
=> feat: enable node deletion with connected links 

src/About.tsx, src/GraphManager/Header/LocaleManager.tsx, src/GraphManager/utils.ts, src/LandingPage/FAQ.tsx, src/LandingPage/MissionStatement.tsx, src/shared/Components.tsx, src/shared/i18n.json
- feat: add whitepaper link to welcome page
- chore: some FAQ cleanup
=> feat: add spanish language option

src/LandingPage/FAQ.tsx
add temporary Impressum (mandatory by law) |-(
=> chore: impressum

package-lock.json, src/GraphManager/GraphEdit/CreateButton.tsx, src/GraphManager/GraphEdit/GraphEdit.test.tsx, src/GraphManager/GraphEdit/GraphEdit.tsx, src/GraphManager/GraphEdit/ModeButton.tsx, src/GraphManager/GraphEdit/NoTouchButton.tsx, src/GraphManager/GraphRenderer.tsx, src/LandingPage/FAQ.tsx
- enable node-clicks by default                           
- disable node dragging by default                        
- edit-mode button switches editing, and not no-touch mode
- TODO: implement no-touch mode by detecting touch events
=> feat: better edit mode

src/GraphManager/GraphEdit/CreateButton.tsx
Fixes a strange combination of read-only mode while trying to add new subjects.
Thank you @EnnoWellmann for noticing! <3
=> fix: enable editing on create button press

src/GraphManager/GraphManager.tsx, src/GraphManager/GraphManagerSigma.tsx, src/GraphManager/GraphRenderer.tsx, src/GraphManager/GraphRendererSigma.tsx
Here's the controller integration you asked for :D
=> fix: controller integration into sigma renderer

src/GraphManager/GraphEdit/ButtonTests.test.tsx, src/GraphManager/GraphEdit/GraphEdit.test.tsx, src/GraphManager/GraphEdit/GraphEdit.tsx, src/GraphManager/GraphEdit/ModeButton.tsx, src/GraphManager/GraphEdit/PopUp.tsx, src/GraphManager/GraphRenderer.tsx, src/HowToLearngraph.tsx, src/shared/i18n.json, src/shared/i18n/German.json, src/shared/i18n/Spanish.json
Added explicit test cases for the Buttons on the Graph, Fixed the playground access issue and translated the Howto page, The dependency location was already changed.
=> fix-button-dep-playground-howto-translation

src/GraphManager/GraphEdit/ButtonTests.test.tsx, src/GraphManager/GraphEdit/GraphEdit.test.tsx, src/GraphManager/GraphEdit/GraphEdit.tsx, src/GraphManager/GraphEdit/ModeButton.tsx, src/GraphManager/GraphEdit/PopUp.tsx, src/GraphManager/GraphRenderer.tsx, src/HowToLearngraph.tsx
- keyboard shortcuts would interfere with default mac shortcuts, so use cmd key as default alterntive
=> fix: use mac cmd key as alternative of ctrl key
